// Objective-C API for talking to github.com/hajimehoshi/ebiten/v2/mobile/ebitenmobileview Go package.
//   gobind -lang=objc github.com/hajimehoshi/ebiten/v2/mobile/ebitenmobileview
//
// File is generated by gobind. Do not edit.

#ifndef __Ebitenmobileview_H__
#define __Ebitenmobileview_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol EbitenmobileviewRenderer;
@class EbitenmobileviewRenderer;
@protocol EbitenmobileviewSetGameNotifier;
@class EbitenmobileviewSetGameNotifier;

@protocol EbitenmobileviewRenderer <NSObject>
- (void)requestRenderIfNeeded;
- (void)setExplicitRenderingMode:(BOOL)explicitRendering;
@end

@protocol EbitenmobileviewSetGameNotifier <NSObject>
- (void)notifySetGame;
@end

FOUNDATION_EXPORT double EbitenmobileviewDeviceScale(void);

FOUNDATION_EXPORT BOOL EbitenmobileviewIsGL(BOOL* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void EbitenmobileviewLayout(double viewWidth, double viewHeight);

FOUNDATION_EXPORT void EbitenmobileviewOnContextLost(void);

FOUNDATION_EXPORT BOOL EbitenmobileviewResume(NSError* _Nullable* _Nullable error);

// skipped function SetGame with unsupported parameter or return types


FOUNDATION_EXPORT void EbitenmobileviewSetRenderer(id<EbitenmobileviewRenderer> _Nullable renderer);

FOUNDATION_EXPORT void EbitenmobileviewSetSetGameNotifier(id<EbitenmobileviewSetGameNotifier> _Nullable setGameNotifier);

FOUNDATION_EXPORT BOOL EbitenmobileviewSetUIView(int64_t uiview, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL EbitenmobileviewSuspend(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL EbitenmobileviewUpdate(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void EbitenmobileviewUpdatePressesOnIOS(long phase, long keyCode, NSString* _Nullable keyString);

FOUNDATION_EXPORT void EbitenmobileviewUpdateTouchesOnIOS(long phase, int64_t ptr, long x, long y);

FOUNDATION_EXPORT BOOL EbitenmobileviewUsesStrictContextRestoration(void);

@class EbitenmobileviewRenderer;

@class EbitenmobileviewSetGameNotifier;

@interface EbitenmobileviewRenderer : NSObject <goSeqRefInterface, EbitenmobileviewRenderer> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)requestRenderIfNeeded;
- (void)setExplicitRenderingMode:(BOOL)explicitRendering;
@end

@interface EbitenmobileviewSetGameNotifier : NSObject <goSeqRefInterface, EbitenmobileviewSetGameNotifier> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)notifySetGame;
@end

#endif
