
// Objective-C API for talking to the following Go packages
//
//	github.com/m110/airplanes/mobile
//	github.com/hajimehoshi/ebiten/v2/mobile/ebitenmobileview
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Airplanes_FRAMEWORK_H__
#define __Airplanes_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Ebitenmobileview.objc.h"
#include "Universe.objc.h"

#endif
